const crops = [
  {
    _id: '1',
    name: 'Arugula',
    soil: 'Well-drained',
    temperature: 45,
    plantingSeason: 'spring',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Eruca_vesicaria',
  },
  {
    _id: '2',
    name: 'Asparagus',
    soil: 'Well-drained',
    temperature: 70,
    plantingSeason: 'spring',
    daysToHarvest: 180,
    url: 'https://en.wikipedia.org/wiki/Asparagus',
  },
  {
    _id: '3',
    name: 'Bean',
    soil: 'Well-drained, right in organic matter',
    temperature: 70,
    plantingSeason: 'spring',
    daysToHarvest: 60,
    url: 'https://en.wikipedia.org/wiki/Bean',
  },
  {
    _id: '4',
    name: 'Beet',
    soil: 'Well-drained',
    temperature: 65,
    plantingSeason: 'spring',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Beetroot',
  },
  {
    _id: '5',
    name: 'Broccoli',
    soil: 'Rich in nitrogen',
    temperature: 50,
    plantingSeason: 'spring',
    daysToHarvest: 55,
    url: 'https://en.wikipedia.org/wiki/Broccoli',
  },
  {
    _id: '6',
    name: 'Brussels Sprout',
    soil: 'Rich, well-drained with organic matter',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 110,
    url: 'https://en.wikipedia.org/wiki/Brussels_sprout',
  },
  {
    _id: '7',
    name: 'Cabbage',
    soil: 'Rich in loam, well-drained',
    temperature: 55,
    plantingSeason: 'spring to late summer',
    daysToHarvest: 70,
    url: 'https://en.wikipedia.org/wiki/Cabbage',
  },
  {
    _id: '8',
    name: 'Carrot',
    soil: 'Loose textured, not too rich in nitrogen',
    temperature: 55,
    plantingSeason: 'spring',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Carrot',
  },
  {
    _id: '9',
    name: 'Chard',
    soil: 'Well drained, fertile & rich in organic matter',
    temperature: 86,
    plantingSeason: 'spring',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Chard',
  },
  {
    _id: '10',
    name: 'Corn',
    soil: 'Loose, well-drained, add nutrients',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 60,
    url: 'https://en.wikipedia.org/wiki/Maize',
  },
  {
    _id: '11',
    name: 'Cucumber',
    soil: 'Well-drained loam rich in organic matter',
    temperature: 65,
    plantingSeason: 'spring',
    daysToHarvest: 55,
    url: 'https://en.wikipedia.org/wiki/Cucumber',
  },
  {
    _id: '12',
    name: 'Eggplant',
    soil: 'Well-drained, average fertility',
    temperature: 70,
    plantingSeason: 'spring',
    daysToHarvest: 115,
    url: 'https://en.wikipedia.org/wiki/Eggplant',
  },
  {
    _id: '13',
    name: 'Garlic',
    soil: 'Deep,rich soil in full sun',
    temperature: 50,
    plantingSeason: 'spring,fall',
    daysToHarvest: 90,
    url: 'https://en.wikipedia.org/wiki/Garlic',
  },
  {
    _id: '14',
    name: 'Kale',
    soil: 'fertile soil rich in organic matter',
    temperature: 60,
    plantingSeason: 'spring, late summer',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Kale',
  },
  {
    _id: '15',
    name: 'Lettuce',
    soil: 'Well-drained',
    temperature: 60,
    plantingSeason: 'spring, fall',
    daysToHarvest: 40,
    url: 'https://en.wikipedia.org/wiki/Lettuce',
  },
  {
    _id: '16',
    name: 'Onion',
    soil: 'Well-drained, neutral pH',
    temperature: 68,
    plantingSeason: 'spring',
    daysToHarvest: 50,
    url: 'https://en.wikipedia.org/wiki/Onion',
  },
  {
    _id: '17',
    name: 'Pea',
    soil: 'Well-drained, fertile soil',
    temperature: 55,
    plantingSeason: 'spring',
    daysToHarvest: 56,
    url: 'https://en.wikipedia.org/wiki/Pea',
  },
  {
    _id: '18',
    name: 'Bell Pepper',
    soil: 'Well-drained, sandy loam',
    temperature: 70,
    plantingSeason: 'spring',
    daysToHarvest: 120,
    url: 'https://en.wikipedia.org/wiki/Capsicum',
  },
  {
    _id: '19',
    name: 'Potato',
    soil: 'Well-drained with plenty of space',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 90,
    url: 'https://en.wikipedia.org/wiki/Potato',
  },
  {
    _id: '20',
    name: 'Radish',
    soil: 'Well-drained',
    temperature: 65,
    plantingSeason: 'spring',
    daysToHarvest: 21,
    url: 'https://en.wikipedia.org/wiki/Radish',
  },
  {
    _id: '21',
    name: 'Edamame',
    soil: 'Well-drained, not too rich in nitrogen',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 75,
    url: 'https://en.wikipedia.org/wiki/Edamame',
  },
  {
    _id: '22',
    name: 'Spinach',
    soil: 'Well-drained',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 37,
    url: 'https://en.wikipedia.org/wiki/Spinach',
  },
  {
    _id: '23',
    name: 'Squash',
    soil: 'Well-drained',
    temperature: 60,
    plantingSeason: 'spring',
    daysToHarvest: 45,
    url: 'https://en.wikipedia.org/wiki/Cucurbita',
  },
  {
    _id: '24',
    name: 'Tomato',
    soil: 'Sandy loam, rich in nutrient, well-drained',
    temperature: 65,
    plantingSeason: 'spring',
    daysToHarvest: 90,
    url: 'https://en.wikipedia.org/wiki/Tomato',
  },
  {
    _id: '25',
    name: 'Turnip',
    soil: 'Rich, loose soil',
    temperature: 40,
    plantingSeason: 'spring',
    daysToHarvest: 35,
    url: 'https://en.wikipedia.org/wiki/Turnip',
  },
];

module.exports = { crops };
